// src/charmData.js
export const CHARM_MAP = {
    "charmCost_1":  { name: "Gathering Swarm", img: "Gathering_Swarm.png" },
    "charmCost_2":  { name: "Wayward Compass", img: "Wayward_Compass.png" },
    "charmCost_3":  { name: "Grubsong", img: "Grubsong.png" },
    "charmCost_4":  { name: "Stalwart Shell", img: "Stalwart_Shell.png" },
    "charmCost_5":  { name: "Baldur Shell", img: "Baldur_Shell.png" },
    "charmCost_6":  { name: "Fury of the Fallen", img: "Fury_of_the_Fallen.png" },
    "charmCost_7":  { name: "Quick Focus", img: "Quick_Focus.png" },
    "charmCost_8":  { name: "Lifeblood Heart", img: "Lifeblood_Heart.png" },
    "charmCost_9":  { name: "Lifeblood Core", img: "Lifeblood_Core.png" },
    "charmCost_10": { name: "Defender's Crest", img: "Defender's_Crest.png" },
    "charmCost_11": { name: "Flukenest", img: "Flukenest.png" },
    "charmCost_12": { name: "Thorns of Agony", img: "Thorns_of_Agony.png" },
    "charmCost_13": { name: "Mark of Pride", img: "Mark_of_Pride.png" },
    "charmCost_14": { name: "Steady Body", img: "Steady_Body.png" },
    "charmCost_15": { name: "Heavy Blow", img: "Heavy_Blow.png" },
    "charmCost_16": { name: "Sharp Shadow", img: "Sharp_Shadow.png" },
    "charmCost_17": { name: "Spore Shroom", img: "Spore_Shroom.png" },
    "charmCost_18": { name: "Longnail", img: "Longnail.png" },
    "charmCost_19": { name: "Shaman Stone", img: "Shaman_Stone.png" },
    "charmCost_20": { name: "Soul Catcher", img: "Soul_Catcher.png" },
    "charmCost_21": { name: "Soul Eater", img: "Soul_Eater.png" },
    "charmCost_22": { name: "Glowing Womb", img: "Glowing_Womb.png" },
    "charmCost_23": { name: "Fragile Heart", img: "Fragile_Heart.png" },
    "charmCost_24": { name: "Fragile Greed", img: "Fragile_Greed.png" },
    "charmCost_25": { name: "Fragile Strength", img: "Fragile_Strength.png" },
    "charmCost_26": { name: "Unbreakable Heart", img: "Unbreakable_Heart.png" },
    "charmCost_27": { name: "Unbreakable Greed", img: "Unbreakable_Greed.png" },
    "charmCost_28": { name: "Unbreakable Strength", img: "Unbreakable_Strength.png" },
    "charmCost_29": { name: "Spell Twister", img: "Spell_Twister.png" },
    "charmCost_30": { name: "Dashmaster", img: "Dashmaster.png" },
    "charmCost_31": { name: "Quick Slash", img: "Quick_Slash.png" },
    "charmCost_32": { name: "Deep Focus", img: "Deep_Focus.png" },
    "charmCost_33": { name: "Grubberfly's Elegy", img: "Grubberfly's_Elegy.png" },
    "charmCost_34": { name: "Hiveblood", img: "Hiveblood.png" },
    "charmCost_35": { name: "Dream Wielder", img: "Dream_Wielder.png" },
    "charmCost_36": { name: "Dash Slash (Nailmaster's Glory)", img: "Nailmaster's_Glory.png" },
    "charmCost_37": { name: "Dreamshield", img: "Dreamshield.png" },
    "charmCost_38": { name: "Weaversong", img: "Weaversong.png" },
    "charmCost_39": { name: "Sprintmaster", img: "Sprintmaster.png" },
    "charmCost_40": { name: "Grimmchild", img: "Grimmchild.png" },

    // Additional non-numbered charms you have provided:
    "charmCost_41": { name: "Joni's Blessing", img: "Joni's_Blessing.png" },
    "charmCost_42": { name: "Carefree Melody", img: "Carefree_Melody.png" },
    "charmCost_43": { name: "Shape of Unn", img: "Shape_of_Unn.png" },
    "charmCost_44": { name: "Kingsoul", img: "Kingsoul.png" },
    "charmCost_45": { name: "Void Heart", img: "Void_Heart.png" },
};
